### PR TITLE
Create ColorPresets.cs

### PR DESCRIPTION
**Pull request by gamedev1020192**
Adding Color presets at the bottom of the color wheel, for quickly saving favorite colors. ColorPresets assists with creating/applying presets.

### CODE REVIEW

**Comment by judah4** [comment]
Was there suppose to be a prefab update using the script?

**Comment by gamedev1020192** [comment]
Hi,

Yes I am still new to GitHub :) I’m still learning the terminology.

How do I push prefab/scene changes? Do I have to clone the project first?

I’ve also made a Picker 2.1 prefab that include the ColorPresets script.

Thank you,
Daniel

**Comment by judah4** [comment]
If you are using github desktop it should check it all in if it's in the git project folder.

**Comment by gamedev1020192** [comment]
Ok, I’ll do that. I’ll let you know when I’ve uploaded everything.

**Comment by judah4** [comment]
Oh, I see what was going on.  Yeah, clone the whole project to your computer and work in the unity project.  Once you are happy with the prefab and scene, commit and sync it back up to this pull request.

**Comment by gamedev1020192** [comment]
So I first clone it with GitHub Desktop, then open it with Unity, make my changes then push it with GitHub Desktop. Is that the workflow?

Daniel

**Comment by judah4** [comment]
I think so.  I'm not familiar with git.  I nearly broke the last pull request

**Comment by gamedev1020192** [comment]
Haha, okay, sounds good.

**Comment by gamedev1020192** [comment]
I had a question, what’s the license? Are you okay with someone using it in a commercial product?

Daniel

**Comment by judah4** [comment]
Which license is for open source, without attribution required?  I started this to share with the community so commercial is fine.

**Comment by gamedev1020192** [comment]
Great, sounds good. It’s a great product, thank you for making it.

**Comment by gamedev1020192** [comment]
Ok, I've committed my changes in the Color-Presets branch. I updated the prefab/scene as well.

**Comment by judah4** [comment]
I think you have to add the commits to the pull request or something

**Comment by gamedev1020192** [comment]
Ok, I created a pull request. Did you get the commit?

**Pull request merged**
